function u = MM_data(t)
%MM_data Use data as input for model of irreversible enzyme reaction.
%
%   u = MM_data(t)
%

%first column: Time (s), second column Influx (M/sec)
inputdata = [0     1e-6;...
             2000  1e-6;...
             2100  4e-6;...
             2200  2e-6;...
             2300  6e-6;...
             2500  6e-6;...
             3000  1e-6;...
             5000  1e-6];

u=interp1(inputdata(:,1),inputdata(:,2),t);	%linear interpolation 
				%see help interp1
